### ISSUE TITLE
CI for runtime issues

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#101]
How can we easily test the built binaries to make sure they run a default config file without problems?

Integration tests?

**Comment by majestrate** [comment]
On Mon, Dec 03, 2018 at 09:06:21PM -0800, Ryan Tharp wrote:
> How can we easily test the built binaries to make sure they run a default config file without problems?

I have a shadow plugin that i can tweak, see shadow: https://shadow.github.io/

target is make shadow

**Comment by liilac** [comment]
This deserves more attention IMO.

We should be writing integration and functional tests in addition to unit tests.  This is invaluable especially for a project such as this where there are direct financial and security/privacy implications to flaws.

I am quite happy to work on tests but I still need to work through the code in order to familiarise myself with it enough to feel confident doing this.

**Comment by neuroscr** [comment]
@michael-loki is tasked with improving unit-tests, it's a huge tasks and he's been attacking but it's going to take a lot of time to get coverage

**Comment by neuroscr** [comment]
closing for now. Michael has improved CI and Tom is carrying on the fight for tooling. Michael's issue #717 best carries on the spirit of this issue.
