### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#105]
Allow lokinet install from homebrew

**Comment by liilac** [comment]
PR made with sample homebrew formula.  Will make a PR against homebrew core repository as well.

**Comment by neuroscr** [comment]
For those not following #110 

https://github.com/Homebrew/homebrew-core/pull/34939

say it was rejected because our repo was not popular enough

**Comment by neuroscr** [comment]
Created #122 to address their blocking

**Comment by liilac** [comment]
Note that my open PR is for setting up our own tap.  It would allow this repository to be used as a tap.

**Comment by liilac** [comment]
How come this was closed, was Homebrew support explicitly decided against, as an install option alongside standard macOS packaging?

**Comment by majestrate** [comment]
On Tue, Apr 16, 2019 at 07:43:35AM +0000, Lilac wrote:
> How come this was closed, was Homebrew support explicitly decided against, as an install option alongside standard macOS packaging?

at the moment it's not a major priority and they already rejected it when we prematurely requested access, probably best to wait for 
lokinet to get more popular.

**Comment by liilac** [comment]
Homebrew rejected it for inclusion in their own repo for not meeting popularity requirements, which have since been met -- it would be merged if a PR was made again now.

That's a separate issue to providing Homebrew packaging though, which support for was finished months ago (see PR #110).  Maintenance burden is updating a line in a 61LOC ruby file if the repo ever changes. etc.

Not sure I see the harm in merging already-complete packaging support for a popular target platform?

**Comment by kuchta** [comment]
Why not use homebrew taps like other non-core sw do? Simple as:

```
brew tap oxen-io/lokinet
brew install lokinet
```
