### ISSUE TITLE
lokinet could use a flag to specify a custom config file

### ISSUE THREAD

**Issue by despair86** [loki-project/loki-network#1346]
```
$ lokinet --win32-daemon [path to custom config file]
```
doesn't work, while
```
$ lokinet [path to custom config file] --win32-daemon
```
ignores the flag completely causing SCM to hang

instead we should do something along the lines of
```
$ lokinet [other params] -F [path to custom config]
```
note the capital F since `-f` is already taken -rick

**Comment by despair86** [comment]
update:
```
$ lokinet --win32-daemon=1 [path to config]
```
works as expected

**Comment by despair86** [comment]
in another pr i'm going to finally get it to run as root (from `$PROGRAMDATA/.lokinet`) so in the service parameters we specify the path to `$PROGRAMDATA/.lokinet/lokinet.ini`

**Comment by jagerman** [comment]
I think that these:
```C++
("install", "install win32 daemon to SCM", cxxopts::value<bool>())(
          "remove", "remove win32 daemon from SCM", cxxopts::value<bool>())(
          "win32-daemon", "do not use interactively", cxxopts::value<bool>())
```
should be without the `cxxopts::value<bool>()` argument, which I *think* turns them into valueless flags rather than options that can be true false (and then check them with `.count("install")` rather than checking the value).  You won't be able to write `lokinet --install 0` to set it to 0, but I don't think that is particularly useful anyway.

(side note: clang format really butchered them)

**Comment by despair86** [comment]
oops forgot to eat my own args before branching to `lokinet_main()`
