### ISSUE TITLE
require ipv6 and ipv4 addresses for relays

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#178]
i have been thinking about this a very short time but i am thinking of requiring ipv4 for client to service node connectivity and ipv6 for inter service node comms. very few internal changes are required since everything is represented as ipv6 internally.

potential positive attributes:

* if you don't advertise ipv4 connectivity you can be implicitly assumed not eligible as a first hop
* if you advertise ipv6 only you can be implicitly assumed a middle hop
* switching to ipv6 only exits will easier as ipv6 connectivity is implied, being nat based is irrelevant as well.

potential negative attributes:

* ipv6 adoption is still not very good
* ipv6 perf is supposed to suck
* ndp sucks balls and is more code to write

**Comment by KeeJef** [comment]
We don't actually need a way to advertise exit or relay status implicitly, when a node registers by staking they can easily (are required to) signal their intention to be a Relay or an Exit, in the registration transaction, which would be included in the RPC call to get the SNode whitelist.

Point 3 still stands, but i think it might be negated by 4, 5 and 6, we should probably still have some ipv4 functionality on exits since its what most people expect and will probably make communicating from exits to servers on the clearnet much easier.

**Comment by majestrate** [comment]
On Sun, Dec 23, 2018 at 06:44:14AM -0800, Kee Jefferys wrote:
> We don't actually need a way to advertise exit or relay status implicitly, when a node registers by staking they can easily (are required to) signal their intention to be a Relay or an Exit, in the registration transaction, which would be included in the RPC call to get the SNode whitelist.
clients have no ability to get this information as just lokinet so it's embedded into the router contact stucture.
we do need a way to advertise exit or relay status, just not exclively implicit. implicit would be a nice to have.
hard depending on lokid for core functionality like knowing who is an exit is a mistake imo.
> 
> Point 3 still stands, but i think it might be negated by 4, 5 and 6, we should probably still have some ipv4 functionality on exits since its what most people expect and will probably make communicating from exits to servers on the clearnet much easier. 
ipv4 nat exits are already implemented and working, this is for future expansion for exit relay opers.
ipv6 only exits don't exclude ipv4 connectivity which can be done via SIIT.

**Comment by neuroscr** [comment]
we have code for this, going to close for now
