### ISSUE TITLE
Disable DNSoverHTTPS

### ISSUE THREAD

**Issue by neuroscr** [loki-project/loki-network#832]
lokinet dns needs to return notfound for special domain

**Comment by despair86** [comment]
"Network administrators may configure their networks as follows to signal that their local DNS resolver implemented special features that make the network unsuitable for DoH:

DNS queries for the A and AAAA records for the domain “use-application-dns.net” must respond with either: a response code other than NOERROR, such as NXDOMAIN (non-existent domain) or SERVFAIL; or respond with NOERROR, but return no A or AAAA records. "

**Comment by jagerman** [comment]
Mozilla: People need to be free from their ISP spying on their browsing habits!
People: Hurray!
Mozilla: So instead we will hand all DNS queries to Cloudflare!
People: Um, wait a second...
Mozilla: Privacy remember, privacy!
ISPs: Wait, we need a loophole so that we can provide high value to our customers by analyzing their browsing habits to offer them more relevant advertising and higher fees for paid prioritization so that we can help them to help themselves improve their lives!
Mozilla: What a great idea, okay here's `use-application-dns.net`
ISPs: Hurray!
People: ... wtf?

**Comment by majestrate** [comment]
I am thinking of implementing dnscrypt in lokinet just so people have a functioning private dns solution

**Comment by unknown-user-9246102101** [comment]
Some more evidence that this poorly thought out "feature" is going to kill people in countries liable to do such things. With claims of heightened security. Timing analysis ruins any attempt to hide what answers you sought via DNS by immediately going to the answers. Not that hard to figure out... https://www.youtube.com/watch?v=8SJorQ9Ufm8

Furthermore, a new vector of attacks gets opened up by hijackers of this DoH, but that's going to happen anyway. Firefox would's face than admit it was a bad idea. Just adding relevant content, with no obligations meant.

**Comment by neuroscr** [comment]
merged in #870
