### ISSUE TITLE
implement DHT key blinding

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-network#85]
probably for version 2 of the protocol however.

**Comment by jagerman** [comment]
To log some more discussion on this:

Currently we look up introsets by .loki addresses, but this means that the SN with an introset gets to see what is being looked up.

Instead what we can do is:

- generate an intro set and encrypt it using the private key.
- hash the public key
- send out this introset record where the distance function now uses the hash rather than the pubkey.

To do an introset lookup we then lookup the hash of the pubkey, get the record, then decrypt it using the pubkey.

The snodes storing the introset can now not know what people are accessing because it won't know the pubkey (unless it learns it in some other way).

**Comment by majestrate** [comment]
solved in #1075
